### ISSUE TITLE
Mrjob in hadoop mode: Error launching job , bad input path : File does not exist

### ISSUE THREAD

**Issue by kvak** [MinerKasch/HadoopWithPython#1]
I'm trying to run the [Mrjob example](https://github.com/MinerKasch/HadoopWithPython/blob/master/python/MapReduce/mrjob/top_salary.py), in pseudo distributed mode.

So I can start the namenode and the datanode:

    start-dfs.sh

returns:

    Starting namenodes on [localhost]
    localhost: starting namenode, logging to /home/me/hadoop-2.7.3/logs/hadoop-me-namenode-me-Notebook-PC.out
    localhost: starting datanode, logging to /home/me/hadoop-2.7.3/logs/hadoop-me-datanode-me-Notebook-PC.out
    Starting secondary namenodes [0.0.0.0]
    0.0.0.0: starting secondarynamenode, logging to /home/me/hadoop-2.7.3/logs/hadoop-me-secondarynamenode-me-Notebook-PC.out

I also have no problem creating the input file structure and copying 
`salaries.csv` unto the hdfs:

    hdfs dfs -mkdir /user/
    hdfs dfs -mkdir /user/me/
    hdfs dfs -mkdir /user/me/input/
    hdfs dfs -put /home/me/Desktop/work/cv/hadoop/salaries.csv /user/me/input/
    hdfs dfs -ls /user/me/input/

returns:

    Found 1 items
    -rw-r--r--   3 me supergroup    1771685 2016-12-24 15:57 /user/me/input/salaries.csv

I also make `top_salaries.py` executable:

    sudo chmod a+x /home/me/Desktop/work/cv/hadoop/top_salaries.py

lauching `top_salaries.py` in local mode also works:

    python2 top_salaries.py -r local salaries.csv > answer.csv

returns:

    No configs found; falling back on auto-configuration
    Creating temp directory /tmp/top_salaries.me.20161224.195052.762894
    Running step 1 of 1...
    Counters: 1
    	warn
    		missing gross=3223
    Counters: 1
    	warn
    		missing gross=3223
    Streaming final output from /tmp/top_salaries.me.20161224.195052.762894/output...
    Removing temp directory /tmp/top_salaries.me.20161224.195052.762894...

however, running this job on the hadoop (putting things together)  `python2 top_salaries.py -r hadoop  hdfs:///user/me/input/salaries.csv` returns:

    No configs found; falling back on auto-configuration
    Looking for hadoop binary in $PATH...
    Found hadoop binary: /home/me/hadoop-2.7.3/bin/hadoop
    Using Hadoop version 2.7.3
    Looking for Hadoop streaming jar in /home/me/hadoop-2.7.3...
    Found Hadoop streaming jar: /home/me/hadoop-2.7.3/share/hadoop/tools/lib/hadoop-streaming-2.7.3.jar
    Creating temp directory /tmp/top_salaries.me.20161224.195201.967990
    Copying local files to hdfs:///user/me/tmp/mrjob/top_salaries.me.20161224.195201.967990/files/...
    Running step 1 of 1...
      session.id is deprecated. Instead, use dfs.metrics.session-id
      Initializing JVM Metrics with processName=JobTracker, sessionId=
      Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
      Cleaning up the staging area file:/tmp/hadoop-me/mapred/staging/me553683497/.staging/job_local553683497_0001
      Error launching job , bad input path : File does not exist: /tmp/hadoop-me/mapred/staging/me553683497/.staging/job_local553683497_0001/files/mrjob.zip#mrjob.zip
      Streaming Command Failed!
    Attempting to fetch counters from logs...
    Can't fetch history log; missing job ID
    No counters found
    Scanning logs for probable cause of failure...
    Can't fetch history log; missing job ID
    Can't fetch task logs; missing application ID
    Step 1 of 1 failed: Command '['/home/me/hadoop-2.7.3/bin/hadoop', 'jar', '/home/me/hadoop-2.7.3/share/hadoop/tools/lib/hadoop-streaming-2.7.3.jar', '-files', 'hdfs:///user/me/tmp/mrjob/top_salaries.me.20161224.195201.967990/files/mrjob.zip#mrjob.zip,hdfs:///user/me/tmp/mrjob/top_salaries.me.20161224.195201.967990/files/setup-wrapper.sh#setup-wrapper.sh,hdfs:///user/me/tmp/mrjob/top_salaries.me.20161224.195201.967990/files/top_salaries.py#top_salaries.py', '-input', 'hdfs:///user/me/input/salaries.csv', '-output', 'hdfs:///user/me/tmp/mrjob/top_salaries.me.20161224.195201.967990/output', '-mapper', 'sh -ex setup-wrapper.sh python top_salaries.py --step-num=0 --mapper', '-combiner', 'sh -ex setup-wrapper.sh python top_salaries.py --step-num=0 --combiner', '-reducer', 'sh -ex setup-wrapper.sh python top_salaries.py --step-num=0 --reducer']' returned non-zero exit status 512

what could be the problem?

**Comment by zachradtka** [comment]
@kvak I just saw this now. I will check into this tonight.

**Comment by kvak** [comment]
Super, thanks! Let me know if I can give more info or remove unnecessary parts of the question!

**Comment by zachradtka** [comment]
What flavor of Hadoop are you running (Hortonworks, Cloudera, Vanilla, etc.)? Also what OS are you running this on?

I have a feeling that either YARN or MR is not started and that is why you are getting this error.

I just spun up a single node instance of Hortonworks with Hadoop 2.7, installed mrjob from pip and it worked.

So I am guessing it is something simple and a little more info should help fix the problem.

**Comment by kvak** [comment]
I use ubuntu (16.04). I do not know what  (Hortonworks, Cloudera, Vanilla, etc.) are: I installed Hadoop-2.7.3 from their website. How can I start YARN, MR? Also, could it be that I have to change `yarn-site.xml`?

**Comment by kvak** [comment]
zachradtka, an user solved my problem at [SO](http://stackoverflow.com/questions/41314376/mrjob-in-hadoop-mode-error-launching-job-bad-input-path-file-does-not-exist)

**Comment by zachradtka** [comment]
Awesome! Glad to hear!

If you are running the other examples, it might be easier to run CDH or Hortonworks. They make implementing small cluster pretty simple.
